language: csharp
solution: testing.sln
install:
    nuget install NUnit.Runners -OutputDirectory testrunner
before_script:
  - nuget restore testing.sln
after_script:
  - ./testrunner/NUnit.ConsoleRunner/tools/nunit3-console.exe HomeExercises/bin/Release/ObjectComparison.dll