language: csharp
solution: testing.sln
install:
  - nuget restore testing.sln
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release testing.sln
  - ./testrunner/NUnit.Runners.3.7.0/tools/nunit-console.exe HomeExercises/bin/Release/ObjectComparison.dll